on:
  push:
    branches: [ master ]
  
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: job1 step1 
        run: |
          echo "Hello job1"
          ls -lah
  Job2:
    needs: Job1
    runs-on: ubuntu-latest
    steps:
      - name: job2 
        run: |
          echo "Hello job2"
          ls -lah
  Job3:
    needs: Job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: job3
        run: | 
          echo "Hello job3"
          ls -lah
  Job4:
    needs: Job3
    runs-on: ubuntu-latest
    steps:
      - name: Job4 
        run: |
          echo "Hello job4"
          cat README.md
