on:
  pull_request:
    types: [opened, reopened]
    branches: [master]
  schedule:
    - cron: '*/5 * * * *'
    - cron: "0 * * * *"
jobs:
  Bonjour_lolo_master:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Lolo master step 1 
        run: echo "Hello Lolo depuis master"
          